name: "PR Verify"
description: "Verifies pull requests by generating and running unit tests."
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  pr_url:
    description: "URL of the pull request to verify"
    required: true
  openai_api_key:
    description: "OpenAI API key"
    required: true
