name: "PR-Verify"
description: "Verifies pull requests by generating and running unit tests."
inputs:
  github_token:
    description: "GitHub token for accessing repository data."
    required: true
  pr_url:
    description: "URL of the pull request to verify."
    required: true
  openai_api_key:
    description: "OpenAI API key for generating unit tests."
    required: true

outputs:
  test_results:
    description: "The results of the unit tests."

runs:
  using: "docker"
  image: "docker://python:3.8"
  args:
    - "main.py"
